"""detect face

Revision ID: 0b68fa14f248
Revises: f5b5b1012abc
Create Date: 2023-02-05 10:27:28.462831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b68fa14f248'
down_revision = 'f5b5b1012abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detect_face',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('width_of_obj', sa.Float(), nullable=True),
    sa.Column('height_of_obj', sa.Float(), nullable=True),
    sa.Column('width_of_img', sa.Float(), nullable=True),
    sa.Column('height_of_img', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detect_face_id'), 'detect_face', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detect_face_id'), table_name='detect_face')
    op.drop_table('detect_face')
    # ### end Alembic commands ###
