version: "3.9"

services:
  deligator:
    container_name: "deligator"
    build: "./deligator"
    volumes:
      - ./deligator/:/app:delegated
    ports:
      - "8800:8000"
    # env_file:
    #   - "./deligator/.env"
    environment:
      - SERVER_HOST=http://localhost:8800
    networks:
      - kafka-network
    command: uvicorn --port 8000 --host 0.0.0.0 main:app --reload

networks:
  kafka-network:
    external: true